[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://happy2332333.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
